server {
    listen 127.0.0.1:8080;
    server_name Webserver/1.0;
    root www;
    index index.html;
    timeout 120;
    cgi_timeout 100;

    error_page 400 /errors/400.html;
    error_page 404 /errors/404.html;
    error_page 5xx /errors/500.html;
    error_page 403 /errors/403.html;
    error_page 405 /errors/405.html;
    
    client_max_body_size 10M;

    location / {
        allowed_methods GET;
        index index.html;
    }

    location /uploads {
        allowed_methods GET POST DELETE;
        root www/uploads;
        upload_dir uploads;
        client_max_body_size 2;
        autoindex on;
    }

    location /old-page {
        return 301 /new-page;
    }

    location /redirect-external {
        return 302 https://www.google.com;
    }

    location /cgi-bin {
        allowed_methods GET POST DELETE;
        root www;
        cgi_timeout 20;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
        cgi_extension .php;
        cgi_path /usr/bin/php-cgi;
    }
}
