server {
    listen 127.0.0.1:8080;
    server_name youpi.test;
    root YoupiBanane;
    index index.html;
    timeout 90M;

    location / {
        allowed_methods GET;
        index index.html;
    }

    location /post_body {
        allowed_methods POST;
        client_max_body_size 100;
        index index.html;
    }

    location /directory/ {
        allowed_methods GET POST;
        root YoupiBanane;
        index youpi.bad_extension;
    }

    location /youpi.bla {
        allowed_methods GET POST;
        root YoupiBanane;
        cgi_extension .bla;
        cgi_path YoupiBanane/cgi_tester;
    }
}